# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HTTPSClient' do

platform :ios, '7.0'

pod 'AFNetworking', '~> 2.3'
pod 'NSHash', '~> 1.0'

end

